create table if not exists public.ingest_logs (
  id bigint generated by default as identity primary key,
  mode text not null,
  city text not null,
  district text not null,
  threshold numeric not null,
  payload jsonb,
  created_at timestamptz default now()
);
